version: '3'

services:
  producer:
    #build: ./producer
    build:
      context: ../
      dockerfile: deployment/producer/Dockerfile
    volumes:
      - ../db/:/db
  consumer:
    #build: ./producer
    build:
      context: ../
      dockerfile: deployment/consumer/Dockerfile
    volumes:
      - ../db/:/db
      - ../output:/output
  #sqlite3:
  #  image: nouchka/sqlite3:latest
  #  stdin_open: true
  #  tty: true
  #  volumes:
  #    - ./db/:/db
  